package main

import "fmt"

func main() {
	fmt.Println("====================")
	pointersFunc()
	fmt.Println("====================")
	structFunc()
	fmt.Println("====================")
	structFunc2()
	fmt.Println("====================")
	structPointers()
	fmt.Println("====================")
	structLiterals()
	fmt.Println("====================")
	arrayFunc()
	fmt.Println("====================")
	slicesFunc()
	fmt.Println("====================")
	slicesPointers()
	fmt.Println("====================")
	sliceLiterals()
	fmt.Println("====================")
	sliceBounds()
	fmt.Println("====================")
	sliceLenCap()
	fmt.Println("====================")
	nilSlice()
	fmt.Println("====================")
	makingSlices()
	fmt.Println("====================")
	slicesOfSlice()
	fmt.Println("====================")
	appendFunc()
	fmt.Println("====================")
	rangeFunc()
	fmt.Println("====================")
	rangeContinued()
	fmt.Println("====================")
	exerciseSlices()
	fmt.Println("====================")
	mapsFunc()
	fmt.Println("====================")
	mapLiterals()
	fmt.Println("====================")
	mutatingMaps()
	fmt.Println("====================")
	exerciseMaps()
	fmt.Println("====================")
	funcValues()
	fmt.Println("====================")
	functionClosures()
	fmt.Println("====================")
	exerciseFunctionClosure()
}
